### ISSUE TITLE
npm start shows Error

### ISSUE THREAD

**Issue by amitshahc** [mrajcok/a2c3-app1#2]
```
D:\Udemy\Angular2-Mark\Git\a2c3-app1>npm start

> a2c3-app1@6.0.0 start D:\Udemy\Angular2-Mark\Git\a2c3-app1
> ng serve

fs.js:972
  binding.stat(pathModule.toNamespacedPath(path));
          ^

Error: ENOENT: no such file or directory, stat 'D:\Udemy\Angular2-Mark\Git\a2c3-app1\src\assets'
    at Object.fs.statSync (fs.js:972:11)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (D:\Udemy\Angular2-Mark\Git\a2c3-app1\node_modules\@angular-devkit\core\node\host.js:212:25)
    at Observable.subscribe (D:\Udemy\Angular2-Mark\Git\a2c3-app1\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Observable.js:162:69)
    at MapOperator.call (D:\Udemy\Angular2-Mark\Git\a2c3-app1\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\map.js:62:23)
    at Observable.subscribe (D:\Udemy\Angular2-Mark\Git\a2c3-app1\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Observable.js:159:22)
    at CatchOperator.call (D:\Udemy\Angular2-Mark\Git\a2c3-app1\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\catchError.js:28:23)
    at Observable.subscribe (D:\Udemy\Angular2-Mark\Git\a2c3-app1\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Observable.js:159:22)
    at MapOperator.call (D:\Udemy\Angular2-Mark\Git\a2c3-app1\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\map.js:62:23)
    at Observable.subscribe (D:\Udemy\Angular2-Mark\Git\a2c3-app1\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Observable.js:159:22)
    at D:\Udemy\Angular2-Mark\Git\a2c3-app1\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\util\subscribeToObservable.js:16:20
    at Object.subscribeToResult (D:\Udemy\Angular2-Mark\Git\a2c3-app1\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\util\subscribeToResult.js:7:45)
    at new ForkJoinSubscriber (D:\Udemy\Angular2-Mark\Git\a2c3-app1\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\observable\forkJoin.js:165:57)
    at Observable._subscribe (D:\Udemy\Angular2-Mark\Git\a2c3-app1\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\observable\forkJoin.js:145:16)
    at Observable.subscribe (D:\Udemy\Angular2-Mark\Git\a2c3-app1\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\Observable.js:162:69)
    at D:\Udemy\Angular2-Mark\Git\a2c3-app1\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\util\subscribeTo.js:22:31
    at Object.subscribeToResult (D:\Udemy\Angular2-Mark\Git\a2c3-app1\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\util\subscribeToResult.js:7:45)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! a2c3-app1@6.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the a2c3-app1@6.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Amit\AppData\Roaming\npm-cache\_logs\2018-10-31T12_58_07_128Z-debug.log

D:\Udemy\Angular2-Mark\Git\a2c3-app1>
```

**Comment by mrajcok** [comment]
Thanks for reporting this.  I removed the src/assets directory, as it is not needed for this project.
